// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/mock_url_shortener.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUrlShortener is a mock of URLShortener interface.
type MockUrlShortener struct {
	ctrl     *gomock.Controller
	recorder *MockUrlShortenerMockRecorder
	isgomock struct{}
}

// MockUrlShortenerMockRecorder is the mock recorder for MockUrlShortener.
type MockUrlShortenerMockRecorder struct {
	mock *MockUrlShortener
}

// NewMockUrlShortener creates a new mock instance.
func NewMockUrlShortener(ctrl *gomock.Controller) *MockUrlShortener {
	mock := &MockUrlShortener{ctrl: ctrl}
	mock.recorder = &MockUrlShortenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlShortener) EXPECT() *MockUrlShortenerMockRecorder {
	return m.recorder
}

// Shorten mocks base method.
func (m *MockUrlShortener) Shorten(ctx context.Context, userID, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shorten", ctx, userID, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shorten indicates an expected call of Shorten.
func (mr *MockUrlShortenerMockRecorder) Shorten(ctx, userID, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shorten", reflect.TypeOf((*MockUrlShortener)(nil).Shorten), ctx, userID, url)
}
